version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: counter_db
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: counter_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
